# Generated by Django 5.2.4 on 2025-09-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrowing',
            options={'verbose_name': 'Borrowing', 'verbose_name_plural': 'Borrowings'},
        ),
        migrations.AlterField(
            model_name='borrowing',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='borrowing',
            table='borrowings',
        ),
    ]
